sysbench.cmdline.options = {
    users_count = {"Count of users for generating the address", 10000}
}

if sysbench.cmdline.command == nil then
   error("Command is required. Supported commands: run")
end

-- Uses prepared statements with bound parameters (rather than string
-- interpolation) so generated values can never be interpreted as SQL,
-- regardless of what characters end up in a random charset.
-- No RETURNING clause here: this statement is executed as a prepared
-- statement, and sysbench's PgSQL driver requests prepared-statement
-- results in binary wire format. fetch_row() would hand back raw binary
-- bytes for address_id (not decimal text), which tonumber() cannot safely
-- interpret. The new address_id is instead fetched via a separate
-- unprepared query below, which always returns text results.
local insert_stmt = "INSERT INTO address (userid, contact_name, street_address, appartment_no, city, pincode, country, contact) " ..
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
local update_stmt = "UPDATE users SET default_address=? WHERE id=?"

local insert_prepared, update_prepared
local ins_userid, ins_contact_name, ins_street_address, ins_appartment_no, ins_city, ins_pincode, ins_country, ins_contact
local upd_address_id, upd_userid


function create_random_string(charSet, minlenght, length)
       -- math.randomseed(os.time())
        randomString = ''
        randomTuple = {}
        for c in charSet:gmatch"." do
           table.insert(randomTuple, c)
        end

        len =sysbench.rand.pareto(minlenght, length)
        for i = 1, len do
           randomString = randomString .. randomTuple[sysbench.rand.uniform(1, #randomTuple)]
        end

        return randomString
end

function generate_street_address()
        local num = sysbench.rand.uniform(1,500)
        local chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
        local street_name = create_random_string(chars, 70,100)
        return num .. ' ' .. street_name
end

function generate_contact_name()
        local chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        local first_name = create_random_string(chars, 6, 20)
        local last_name = create_random_string(chars,6,20)
        return first_name .. ' ' .. last_name
end

function prepare_statements()
        insert_prepared = con:prepare(insert_stmt)
        ins_userid = insert_prepared:bind_create(sysbench.sql.type.BIGINT)
        ins_contact_name = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 200)
        ins_street_address = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 200)
        ins_appartment_no = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 50)
        ins_city = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 100)
        ins_pincode = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 10)
        ins_country = insert_prepared:bind_create(sysbench.sql.type.VARCHAR, 100)
        ins_contact = insert_prepared:bind_create(sysbench.sql.type.BIGINT)
        insert_prepared:bind_param(ins_userid, ins_contact_name, ins_street_address, ins_appartment_no,
                ins_city, ins_pincode, ins_country, ins_contact)

        update_prepared = con:prepare(update_stmt)
        upd_address_id = update_prepared:bind_create(sysbench.sql.type.BIGINT)
        upd_userid = update_prepared:bind_create(sysbench.sql.type.BIGINT)
        update_prepared:bind_param(upd_address_id, upd_userid)
end

function execute_insert(userid, contact_name, street_address, appartment_no, city, pincode, country, contact)
        ins_userid:set(userid)
        ins_contact_name:set(contact_name)
        ins_street_address:set(street_address)
        ins_appartment_no:set(appartment_no)
        ins_city:set(city)
        -- pincode column is varchar; contact column is bigint. Coerce
        -- explicitly rather than relying on implicit FFI conversions.
        ins_pincode:set(tostring(pincode))
        ins_country:set(country)
        ins_contact:set(tonumber(contact))

        insert_prepared:execute()
        -- lastval() returns the value most recently generated by an
        -- IDENTITY/serial column in this session, which is address_id
        -- from the INSERT above. con:query() uses PQexec (not a prepared
        -- statement), so the result is always plain text, unlike
        -- fetch_row() on a prepared statement's result.
        local id_result = con:query("SELECT lastval()")
        local addressid = tonumber(id_result:fetch_row()[1])

        upd_address_id:set(addressid)
        upd_userid:set(userid)
        update_prepared:execute()
end

function generate_city()
        local chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        local city = create_random_string(chars, 8, 30)
        return city
end

function generate_country()
        local country_list = {"India","Singapore","USA","England","Scotland", "Malaysia","Australia","New Zealand","Indonesia","Germany","France","Belgium","Fiji"}
        local list_selector = sysbench.rand.uniform(1, 13)
        return country_list[list_selector]
end

function generate_contact()
        local first_digit = sysbench.rand.uniform(3, 9)
        local nums = '1234567890'
        return first_digit .. create_random_string(nums, 6, 12)
end

function thread_init()

        drv = sysbench.sql.driver()
        con = drv:connect()

        prepare_statements()
end

function thread_done()

        insert_prepared:close()
        update_prepared:close()
        con:disconnect()
end
function event()

        local userid = sysbench.rand.uniform(1, sysbench.opt.users_count)
        local contact_name = generate_contact_name()
        local street_address = generate_street_address()
        local appartment_no = sysbench.rand.uniform(1, 20) .. '-' .. sysbench.rand.uniform(1,30)
        local city = generate_city() 
        local pincode = sysbench.rand.uniform(30000, 88888)
        local city = generate_city()
        local country = generate_country()
        local contact = generate_contact()

        if not sysbench.opt.skip_trx then
                con:query("BEGIN")
        end

        execute_insert(userid, contact_name, street_address, appartment_no, city, pincode, country, contact)

        if not sysbench.opt.skip_trx then
                con:query("COMMIT")
        end
end
